module.exports = {
  FULL_NAME_REQUIRED: {
    de: "Vollständiger Name ist erforderlich",
    en: "Full name is required",
    es: "Se requiere nombre completo",
    fr: "Nom complet requis",
    it: "Nome completo richiesto",
  },
  EMAIL_REQUIRED: {
    en: "Email is required",
    de: "E-Mail ist erforderlich",
    es: "Se requiere correo electrónico",
    fr: "E-mail requis",
    it: "Email richiesta",
  },
  PASSWORD_REQUIRED: {
    en: "Password is required",
    de: "Passwort wird benötigt",
    es: "Se requiere contraseña",
    fr: "Mot de passe requis",
    it: "Password richiesta",
  },
  INITIALS_REQUIRED: {
    en: "Initials is required",
    de: "Initialen sind erforderlich",
    es: "Se requieren iniciales",
    fr: "Initiales requises",
    it: "Iniziali richieste",
  },
  CODE_REQUIRED: {
    en: "Code is required",
    de: "Code ist erforderlich",
    es: "Se requiere código",
    fr: "Code requis",
    it: "Codice richiesto",
  },
  CURRENT_PASSWORD_REQUIRED: {
    en: "Current password is required",
    de: "Aktuelles Passwort ist erforderlich",
    es: "Se requiere contraseña actual",
    fr: "Mot de passe actuel requis",
    it: "Password attuale richiesta",
  },
  OTP_VERIFICATION_REQUIRED: {
    en: "OTP verification is required",
    de: "OTP-Verifizierung ist erforderlich",
    es: "Se requiere verificación OTP",
    fr: "Vérification OTP requise",
    it: "Verifica OTP richiesta",
  },
  NEW_PASSWORD_REQUIRED: {
    en: "New password is required",
    de: "Neues Passwort erforderlich",
    es: "Se requiere nueva contraseña",
    fr: "Nouveau mot de passe requis",
    it: "Nuova password richiesta",
  },
  SNORING_DURATION_REQUIRED: {
    en: "Snoring duration is required",
    de: "Schnarchdauer ist erforderlich",
    es: "Se requiere duración del ronquido",
    fr: "Durée du ronflement requise",
    it: "Durata del russare richiesta",
  },
  SESSION_DURATION_REQUIRED: {
    en: "Session duration is required",
    de: "Sitzungsdauer ist erforderlich",
    es: "Se requiere duración de la sesión",
    fr: "Durée de la session requise",
    it: "Durata della sessione richiesta",
  },
  START_TIME_REQUIRED: {
    en: "Start time is required",
    de: "Startzeit ist erforderlich",
    es: "Se requiere hora de inicio",
    fr: "Heure de début requise",
    it: "Orario di inizio richiesto",
  },
  AUDIO_URL_REQUIRED: {
    en: "Audio url is required",
    de: "Audio-URL ist erforderlich",
    es: "Se requiere URL de audio",
    fr: "URL audio requise",
    it: "URL audio richiesta",
  },
  TIME_ZONE_REQUIRED: {
    en: "Time zone is required",
    de: "Zeitzone ist erforderlich",
    es: "Se requiere zona horaria",
    fr: "Fuseau horaire requis",
    it: "Fuso orario richiesto",
  },
  TYPE_REQUIRED: {
    en: "Type is required",
    de: "Typ ist erforderlich",
    es: "Se requiere tipo",
    fr: "Type requis",
    it: "Tipo richiesto",
  },
  MONTH_REQUIRED: {
    en: "Month is required",
    de: "Monat ist erforderlich",
    es: "Se requiere mes",
    fr: "Mois requis",
    it: "Mese richiesto",
  },
  TEAM_NAME_REQUIRED: {
    en: "Group name is required",
    de: "Gruppenname ist erforderlich",
    es: "Se requiere nombre de grupo",
    fr: "Le nom du groupe est requis",
    it: "È richiesto il nome del gruppo"
  },
  TEAM_MEMBER_NAME_REQUIRED: {
    en: "Group member name is required",
    de: "Der Name des Gruppenmitglieds ist erforderlich",
    es: "Se requiere el nombre del miembro del grupo",
    fr: "Le nom du membre du groupe est requis",
    it: "È richiesto il nome del membro del gruppo"
  },
  TEAM_MEMBER_ALREADY_IN_A_TEAM:
  {
    en: "Group member is already in a group",
    de: "Gruppenmitglied ist bereits in einer Gruppe",
    es: "El miembro del grupo ya está en un grupo",
    fr: "Le membre du groupe est déjà dans un groupe",
    it: "Il membro del gruppo è già in un gruppo"
  },
  TEAM_ID_REQUIRED: {
    en: "Group ID is required",
    de: "Gruppen-ID ist erforderlich",
    es: "Se requiere identificación del grupo",
    fr: "L'identifiant du groupe est requis",
    it: "È richiesto l'ID del gruppo"
  },
  TEAM_SAME_NAME:
  {
    en: "Group name already exist",
    de: "Gruppenname existiert bereits",
    es: "El nombre del grupo ya existe",
    fr: "Le nom du groupe existe déjà",
    it: "Il nome del gruppo esiste già" 
  },
  ENROLLMENT_CODE_REQUIRED: {
    en: "Enrollment code is required",
    de: "Ein Registrierungscode ist erforderlich",
    es: "Se requiere código de inscripción",
    fr: "Le code d'inscription est requis",
    it: "È richiesto il codice di iscrizione",
  },
  TEAM_MEMBER_ID_REQUIRED: {
    en: "Team member id is required",
    de: "Teammitglieds-ID ist erforderlich",
    es: "Se requiere identificación del miembro del equipo",
    fr: "L'identifiant du membre de l'équipe est requis",
    it: "È richiesto l'ID del membro del team",
  },
  STATUS_REQUIRED: {
    en: "Status is required",
    de: "Der Status ist erforderlich",
    es: "Se requiere estado",
    fr: "Le statut est requis",
    it: "È richiesto lo stato",
  },
  USER_ID_REQUIRED: {
    en: "User id is required",
    de: "Benutzer-ID ist erforderlich",
    es: "Se requiere identificación de usuario",
    fr: "L'identifiant de l'utilisateur est requis",
    it: "È richiesto l'ID dell'utente",
  },
  SOCKET_ID_REQUIRED: {
    en: "Socket id is required",
    de: "Socket-ID ist erforderlich",
    es: "Se requiere identificación de socket",
    fr: "L'identifiant du socket est requis",
    it: "È richiesto l'ID del socket",
  },
  USER_TYPE_REQUIRED: {
    en: "User type is required",
    de: "Benutzertyp ist erforderlich",
    es: "Se requiere tipo de usuario",
    fr: "Le type d'utilisateur est requis",
    it: "È richiesto il tipo di utente",
  },
  PASSWORD_SIX_DIGIT: {
    en: "Password should be at least 6 characters",
    de: "Das Passwort sollte mindestens 6 Zeichen lang sein",
    es: "La contraseña debe tener al menos 6 caracteres",
    fr: "Le mot de passe doit comporter au moins 6 caractères",
    it: "La password deve essere di almeno 6 caratteri",
  },
  EMAIL_PASSWORD_NOT_CORRECT: {
    en: "Email or password is not correct",
    de: "E-Mail oder Passwort ist nicht korrekt",
    es: "El correo electrónico o la contraseña no son correctos",
    fr: "L'e-mail ou le mot de passe n'est pas correct",
    it: "Email o password non corretti",
  },
  EMAIL_NOT_VERIFIED: {
    en: "Your email is not verified. Check your email to verify email",
    de: "Ihre E-Mail ist nicht verifiziert. Überprüfen Sie Ihre E-Mail, um die E-Mail zu bestätigen",
    es: "Su correo electrónico no está verificado. Revise su correo electrónico para verificarlo",
    fr: "Votre e-mail n'est pas vérifié. Vérifiez votre e-mail pour le vérifier",
    it: "La tua email non è verificata. Controlla la tua email per verificarla",
  },
  USER_NOT_FOUND: {
    en: "User not found",
    de: "Benutzer nicht gefunden",
    es: "Usuario no encontrado",
    fr: "Utilisateur introuvable",
    it: "Utente non trovato",
  },
  AUTHORIZATION_DENIED: {
    en: "Authorization denied",
    de: "Autorisierung verweigert",
    es: "Autorización denegada",
    fr: "Autorisation refusée",
    it: "Autorizzazione negata",
  },
  CODE_NOT_CORRECT_OR_EXPIRED: {
    en: "Code has been expired or may be not correct",
    de: "Der Code ist abgelaufen oder möglicherweise nicht korrekt",
    es: "El código ha expirado o puede que no sea correcto",
    fr: "Le code a expiré ou peut-être pas correct",
    it: "Il codice è scaduto o potrebbe non essere corretto",
  },
  CURRENT_PASSWORD_NOT_CORRECT: {
    en: "Current password is not correct",
    de: "Aktuelles Passwort ist nicht korrekt",
    es: "La contraseña actual no es correcta",
    fr: "Le mot de passe actuel n'est pas correct",
    it: "La password attuale non è corretta",
  },
  UNSUPPORTED_TYPE: {
    en: "Unsupported type",
    de: "Nicht unterstützter Typ",
    es: "Tipo no soportado",
    fr: "Type non pris en charge",
    it: "Tipo non supportato",
  },
  UNSUPPORTED_STATUS: {
    en: "Unsupported status",
    de: "Nicht unterstützter Status",
    es: "Estado no soportado",
    fr: "Statut non pris en charge",
    it: "Stato non supportato",
  },
  UNSUPPORTED_USER_TYPE: {
    en: "Unsupported user type",
    de: "Nicht unterstützter Benutzertyp",
    es: "Tipo de usuario no soportado",
    fr: "Type d'utilisateur non pris en charge",
    it: "Tipo di utente non supportato",
  },
  TEAM_REQUIRED_BEFORE_MEMBER: {
    en: "Group should exist before adding a member",
    de: "Die Gruppe sollte vorhanden sein, bevor ein Mitglied hinzugefügt wird",
    es: "El grupo debe existir antes de añadir un miembro",
    fr: "Le groupe doit exister avant d'ajouter un membre",
    it: "Il gruppo deve esistere prima di aggiungere un membro"
  },
  CANNOT_SELF_CALL: {
    en: "You cannot call yourself",
    de: "Sie können sich nicht selbst anrufen",
    es: "No puedes llamarte a ti mismo",
    fr: "Vous ne pouvez pas vous appeler vous-même",
    it: "Non puoi chiamarti da solo",
  },
  TEAM_ALREADY_EXIST: {
    en: "Team already exist",
    de: "Team existiert bereits",
    es: "El equipo ya existe",
    fr: "L'équipe existe déjà",
    it: "Il team esiste già",
  },
  TEAM_NOT_EXIST: {
    en: "Team not exist",
    de: "Mannschaft existiert nicht",
    es: "El equipo no existe",
    fr: "L'équipe n'existe pas",
    it: "Il team non esiste",
  },
  TEAM_MEMBER_NOT_EXIST: {
    en: "Team member not exist",
    de: "Teammitglied existiert nicht",
    es: "El miembro del equipo no existe",
    fr: "Le membre de l'équipe n'existe pas",
    it: "Il membro del team non esiste",
  },
  TEAM_MEMBER_ALREADY_EXIST_WITH_NAME: {
    en: "Group member already exists with this name",
    de: "Es existiert bereits ein Gruppenmitglied mit diesem Namen",
    es: "El miembro del grupo ya existe con este nombre",
    fr: "Le membre du groupe existe déjà avec ce nom",
    it: "Il membro del gruppo esiste già con questo nome"
  },
  TEAM_MEMBER_ALREADY_BLOCKED: {
    en: "Team member is already blocked",
    de: "Teammitglied ist bereits gesperrt",
    es: "El miembro del equipo ya está bloqueado",
    fr: "Le membre de l'équipe est déjà bloqué",
    it: "Il membro del team è già bloccato",
  },
  TEAM_MEMBER_IS_NOT_BLOCKED: {
    en: "Team member is not blocked",
    de: "Teammitglied ist nicht blockiert",
    es: "El miembro del equipo no está bloqueado",
    fr: "Le membre de l'équipe n'est pas bloqué",
    it: "Il membro del team non è bloccato",
  },
  NOT_PART_OF_TEAM: {
    en: "You cannot call this user because you are not part of his team",
    de: "Sie können diesen Benutzer nicht anrufen, da Sie nicht zu seinem Team gehören",
    es: "No puedes llamar a este usuario porque no eres parte de su equipo",
    fr: "Vous ne pouvez pas appeler cet utilisateur car vous ne faites pas partie de son équipe",
    it: "Non puoi chiamare questo utente perché non fai parte del suo team",
  },
  DID_NOT_CALL_THIS_MEMBER: {
    en: "You didn't call this team member",
    de: "Sie haben dieses Teammitglied nicht angerufen",
    es: "No llamaste a este miembro del equipo",
    fr: "Vous n'avez pas appelé ce membre de l'équipe",
    it: "Non hai chiamato questo membro del team",
  },
  DID_NOT_CALLED_BY_USER: {
    en: "This user didn't called you",
    de: "Dieser Benutzer hat Sie nicht angerufen",
    es: "Este usuario no te llamó",
    fr: "Cet utilisateur ne vous a pas appelé",
    it: "Questo utente non ti ha chiamato",
  },
  DID_NOT_CALLED_BY_TEAM_MEMBER: {
    en: "This team member didn't called you",
    de: "Dieses Teammitglied hat Sie nicht angerufen",
    es: "Este miembro del equipo no te llamó",
    fr: "Ce membre de l'équipe ne vous a pas appelé",
    it: "Questo membro del team non ti ha chiamato",
  },
  CALL_ALREADY_ANSWERED: {
    en: "This call is already answered",
    de: "Dieser Anruf wurde bereits entgegengenommen",
    es: "Esta llamada ya fue respondida",
    fr: "Cet appel a déjà été répondu",
    it: "Questa chiamata è già stata risposta",
  },
  SUBSCRIPTION_NEEDED: {
    en: "Please subscribe",
    de: "Bitte abonnieren",
    es: "Por favor, suscríbete",
    fr: "Veuillez vous abonner",
    it: "Per favore, sottoscrivi",
  },
  DOCTOR_PERMISSION_NEEDED: {
    en: "You need to be a doctor to continue",
    de: "Sie müssen Arzt sein, um fortzufahren",
    es: "Necesitas ser médico para continuar",
    fr: "Vous devez être médecin pour continuer",
    it: "Devi essere un medico per continuare",
  },
  ONLY_TEAM_MEMBER_CAN_ACCESS: {
    en: "Only team member can access",
    de: "Nur Teammitglieder haben Zugriff",
    es: "Solo los miembros del equipo pueden acceder",
    fr: "Seul le membre de l'équipe peut accéder",
    it: "Solo i membri del team possono accedere",
  },
  ONLY_DOCTOR_CAN_ACCESS: {
    en: "Only doctor can access",
    de: "Nur der Arzt hat Zugriff",
    es: "Solo el médico puede acceder",
    fr: "Seul le médecin peut accéder",
    it: "Solo il medico può accedere",
  },
  MESSAGE_TEXT_REQUIRED: {
    en: "Text is required",
    de: "Text ist erforderlich",
    es: "Se requiere texto",
    fr: "Le texte est requis",
    it: "Il testo è obbligatorio",
  },
  PREDEFINED_MESSAGE_EXIST: {
    en: "This message is already exist",
    de: "Diese Nachricht ist bereits vorhanden",
    es: "Este mensaje ya existe",
    fr: "Ce message existe déjà",
    it: "Questo messaggio esiste già",
  },
  PREDEFINED_MESSAGE_ID_REQUIRED: {
    en: "Predefined Message id required",
    de: "Vordefinierte Nachrichten-ID erforderlich",
    es: "Se requiere ID de mensaje predefinido",
    fr: "L'ID du message prédéfini est requis",
    it: "L'ID del messaggio predefinito è obbligatorio",
  },
  PREDEFINED_MESSAGE_NOT_FOUND: {
    en: "Predefined Message not found",
    de: "Vordefinierte Nachricht nicht gefunden",
    es: "Mensaje predefinido no encontrado",
    fr: "Message prédéfini introuvable",
    it: "Messaggio predefinito non trovato",
  },
  EMAIL_EXIST: {
    en: "Email already exist",
    de: "E-Mail existiert bereits",
    es: "El correo electrónico ya existe",
    fr: "L'e-mail existe déjà",
    it: "L'email esiste già",
  },
  FCM_TOKEN_REQUIRED: {
    en: "Token is required",
    de: "Token ist erforderlich",
    es: "Se requiere token",
    fr: "Le jeton est requis",
    it: "Il token è obbligatorio",
  },
  SUBSCRIPTION_ID_REQUIRED: {
    en: "Subscription id is required",
    de: "Abonnement-ID ist erforderlich",
    es: "Se requiere ID de suscripción",
    fr: "L'ID d'abonnement est requis",
    it: "L'ID dell'abbonamento è obbligatorio",
  },
  SUBSCRIPTION_NOT_FOUND: {
    en: "Subscription not found",
    de: "Abonnement nicht gefunden",
    es: "Suscripción no encontrada",
    fr: "Abonnement introuvable",
    it: "Abbonamento non trovato",
  },
  SUBSCRIPTION_CODE_REQUIRED: {
    en: "Subscription code is required",
    de: "Abonnementcode ist erforderlich",
    es: "Se requiere código de suscripción",
    fr: "Le code d'abonnement est requis",
    it: "Il codice di abbonamento è obbligatorio",
  },
  CANNOT_ADD_MORE_TEMPLATES: {
    en: "Your subscription plan doesn't allow more text templates",
    de: "Ihr Abonnement lässt keine weiteren Textvorlagen zu",
    es: "Tu plan de suscripción no permite más plantillas de texto",
    fr: "Votre plan d'abonnement ne permet pas plus de modèles de texte",
    it: "Il tuo piano di abbonamento non consente più modelli di testo",
  },
  CANNOT_ADD_MORE_MEMBERS: {
    en: "Your subscription plan doesn't allow more members",
    de: "Ihr Abonnementplan lässt keine weiteren Mitglieder zu",
    es: "Tu plan de suscripción no permite más miembros",
    fr: "Votre plan d'abonnement ne permet pas plus de membres",
    it: "Il tuo piano di abbonamento non consente più membri",
  },
  RANK_REQUIRED: {
    en: "Rank is required",
    de: "Rang ist erforderlich",
    es: "Se requiere rango",
    fr: "Le rang est requis",
    it: "Il rango è obbligatorio",
  },
  RANK_SHOULD_NUMBER: {
    en: "Rank should be a number",
    de: "Der Rang sollte eine Zahl sein",
    es: "El rango debe ser un número",
    fr: "Le rang doit être un nombre",
    it: "Il rango deve essere un numero",
  },
  ORDERS_ARRAY_EMPTY: {
    en: "Orders array cannot be empty",
    de: "Das Order-Array darf nicht leer sein",
    es: "El arreglo de pedidos no puede estar vacío",
    fr: "Le tableau des commandes ne peut pas être vide",
    it: "L'array degli ordini non può essere vuoto",
  },
  ONE_MORE_USER_NOT_EXIST: {
    en: "One or more user doesn't exist",
    de: "Mindestens ein Benutzer existiert nicht",
    es: "Uno o más usuarios no existen",
    fr: "Un ou plusieurs utilisateurs n'existent pas",
    it: "Uno o più utenti non esistono",
  },
  USER_ORDER_NOT_FOUND:{
    en: "User order not found",
    de: "Benutzerreihenfolge nicht gefunden",
    es: "Orden de usuario no encontrado",
    fr: "Ordre de l'utilisateur non trouvé",
    it: "Ordine dell'utente non trovato",
  },
};
